use classmanage_Library;
go
delete from teacher;
delete from appointment;
delete from class
go

insert into teacher values('20190001','王小超','123456');
insert into teacher values('20190002','汪晓银','123456');

insert into class   values('0001','模拟电子电路','王小超','50');
insert into class   values('0002','数字电子电路','汪晓银','50');

insert into appointment values('1','1','1','0001','模拟电子电路','20190001','王小超','1');


insert into appointment values('1','1','2','无','无','无','无','0');
insert into appointment values('1','1','3','无','无','无','无','0');
insert into appointment values('1','1','4','无','无','无','无','0');
insert into appointment values('1','1','5','无','无','无','无','0');
insert into appointment values('1','2','1','无','无','无','无','0');
insert into appointment values('1','2','2','无','无','无','无','0');
insert into appointment values('1','2','3','无','无','无','无','0');
insert into appointment values('1','2','4','无','无','无','无','0');
insert into appointment values('1','2','5','无','无','无','无','0');
insert into appointment values('1','3','1','无','无','无','无','0');
insert into appointment values('1','3','2','无','无','无','无','0');
insert into appointment values('1','3','3','无','无','无','无','0');
insert into appointment values('1','3','4','无','无','无','无','0');
insert into appointment values('1','3','5','无','无','无','无','0');
insert into appointment values('1','4','1','无','无','无','无','0');
insert into appointment values('1','4','2','无','无','无','无','0');
insert into appointment values('1','4','3','无','无','无','无','0');
insert into appointment values('1','4','4','无','无','无','无','0');
insert into appointment values('1','4','5','无','无','无','无','0');
insert into appointment values('1','5','1','无','无','无','无','0');
insert into appointment values('1','5','2','无','无','无','无','0');
insert into appointment values('1','5','3','无','无','无','无','0');
insert into appointment values('1','5','4','无','无','无','无','0');
insert into appointment values('1','5','5','无','无','无','无','0');
insert into appointment values('2','1','1','无','无','无','无','0');
insert into appointment values('2','1','2','无','无','无','无','0');
insert into appointment values('2','1','3','无','无','无','无','0');
insert into appointment values('2','1','4','无','无','无','无','0');
insert into appointment values('2','1','5','无','无','无','无','0');
insert into appointment values('2','2','1','无','无','无','无','0');
insert into appointment values('2','2','2','无','无','无','无','0');
insert into appointment values('2','2','3','无','无','无','无','0');
insert into appointment values('2','2','4','无','无','无','无','0');
insert into appointment values('2','2','5','无','无','无','无','0');
insert into appointment values('2','3','1','无','无','无','无','0');
insert into appointment values('2','3','2','无','无','无','无','0');
insert into appointment values('2','3','3','无','无','无','无','0');
insert into appointment values('2','3','4','无','无','无','无','0');
insert into appointment values('2','3','5','无','无','无','无','0');
insert into appointment values('2','4','1','无','无','无','无','0');
insert into appointment values('2','4','2','无','无','无','无','0');
insert into appointment values('2','4','3','无','无','无','无','0');
insert into appointment values('2','4','4','无','无','无','无','0');
insert into appointment values('2','4','5','无','无','无','无','0');
insert into appointment values('2','5','1','无','无','无','无','0');
insert into appointment values('2','5','2','无','无','无','无','0');
insert into appointment values('2','5','3','无','无','无','无','0');
insert into appointment values('2','5','4','无','无','无','无','0');
insert into appointment values('2','5','5','无','无','无','无','0');
insert into appointment values('3','1','1','无','无','无','无','0');
insert into appointment values('3','1','2','无','无','无','无','0');
insert into appointment values('3','1','3','无','无','无','无','0');
insert into appointment values('3','1','4','无','无','无','无','0');
insert into appointment values('3','1','5','无','无','无','无','0');
insert into appointment values('3','2','1','无','无','无','无','0');
insert into appointment values('3','2','2','无','无','无','无','0');
insert into appointment values('3','2','3','无','无','无','无','0');
insert into appointment values('3','2','4','无','无','无','无','0');
insert into appointment values('3','2','5','无','无','无','无','0');
insert into appointment values('3','3','1','无','无','无','无','0');
insert into appointment values('3','3','2','无','无','无','无','0');
insert into appointment values('3','3','3','无','无','无','无','0');
insert into appointment values('3','3','4','无','无','无','无','0');
insert into appointment values('3','3','5','无','无','无','无','0');
insert into appointment values('3','4','1','无','无','无','无','0');
insert into appointment values('3','4','2','无','无','无','无','0');
insert into appointment values('3','4','3','无','无','无','无','0');
insert into appointment values('3','4','4','无','无','无','无','0');
insert into appointment values('3','4','5','无','无','无','无','0');
insert into appointment values('3','5','1','无','无','无','无','0');
insert into appointment values('3','5','2','无','无','无','无','0');
insert into appointment values('3','5','3','无','无','无','无','0');
insert into appointment values('3','5','4','无','无','无','无','0');
insert into appointment values('3','5','5','无','无','无','无','0');
insert into appointment values('4','1','1','无','无','无','无','0');
insert into appointment values('4','1','2','无','无','无','无','0');
insert into appointment values('4','1','3','无','无','无','无','0');
insert into appointment values('4','1','4','无','无','无','无','0');
insert into appointment values('4','1','5','无','无','无','无','0');
insert into appointment values('4','2','1','无','无','无','无','0');
insert into appointment values('4','2','2','无','无','无','无','0');
insert into appointment values('4','2','3','无','无','无','无','0');
insert into appointment values('4','2','4','无','无','无','无','0');
insert into appointment values('4','2','5','无','无','无','无','0');
insert into appointment values('4','3','1','无','无','无','无','0');
insert into appointment values('4','3','2','无','无','无','无','0');
insert into appointment values('4','3','3','无','无','无','无','0');
insert into appointment values('4','3','4','无','无','无','无','0');
insert into appointment values('4','3','5','无','无','无','无','0');
insert into appointment values('4','4','1','无','无','无','无','0');
insert into appointment values('4','4','2','无','无','无','无','0');
insert into appointment values('4','4','3','无','无','无','无','0');
insert into appointment values('4','4','4','无','无','无','无','0');
insert into appointment values('4','4','5','无','无','无','无','0');
insert into appointment values('4','5','1','无','无','无','无','0');
insert into appointment values('4','5','2','无','无','无','无','0');
insert into appointment values('4','5','3','无','无','无','无','0');
insert into appointment values('4','5','4','无','无','无','无','0');
insert into appointment values('4','5','5','无','无','无','无','0');